// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID          int64
	EntityType  sql.NullString
	EntityID    sql.NullString
	Action      sql.NullString
	PerformedBy sql.NullString
	CreatedAt   sql.NullString
}

type Organizer struct {
	TelegramID string
	Name       sql.NullString
	LogoUrl    sql.NullString
	CreatedAt  sql.NullString
}

type President struct {
	TelegramID string
}

type TournamentDraft struct {
	DraftUuid           string
	TournamentClass     sql.NullString
	RequestedBy         sql.NullString
	Name                sql.NullString
	Format              sql.NullString
	TimeControl         sql.NullString
	StartDatetime       sql.NullString
	EndDatetime         sql.NullString
	Timezone            sql.NullString
	Capacity            sql.NullInt64
	Visibility          sql.NullString
	Prizes              sql.NullString
	OrganizerTelegramID sql.NullString
	Rationale           sql.NullString
	Status              sql.NullString
	CreatedAt           sql.NullString
	UpdatedAt           sql.NullString
}

type User struct {
	TelegramID      string
	LichessUsername sql.NullString
	IsWhitelisted   sql.NullInt64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}
