// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const approveDraft = `-- name: ApproveDraft :exec
UPDATE tournament_drafts
SET status = 'approved',
    updated_at = ?
WHERE draft_uuid = ?
AND status = 'submitted'
`

type ApproveDraftParams struct {
	UpdatedAt sql.NullString
	DraftUuid string
}

func (q *Queries) ApproveDraft(ctx context.Context, arg ApproveDraftParams) error {
	_, err := q.db.ExecContext(ctx, approveDraft, arg.UpdatedAt, arg.DraftUuid)
	return err
}

const createDraft = `-- name: CreateDraft :exec
INSERT INTO tournament_drafts (
    draft_uuid,
    tournament_class,
    requested_by,
    name,
    format,
    time_control,
    start_datetime,
    end_datetime,
    timezone,
    capacity,
    visibility,
    prizes,
    organizer_telegram_id,
    rationale,
    status,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'draft', ?)
`

type CreateDraftParams struct {
	DraftUuid           string
	TournamentClass     sql.NullString
	RequestedBy         sql.NullString
	Name                sql.NullString
	Format              sql.NullString
	TimeControl         sql.NullString
	StartDatetime       sql.NullString
	EndDatetime         sql.NullString
	Timezone            sql.NullString
	Capacity            sql.NullInt64
	Visibility          sql.NullString
	Prizes              sql.NullString
	OrganizerTelegramID sql.NullString
	Rationale           sql.NullString
	CreatedAt           sql.NullString
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) error {
	_, err := q.db.ExecContext(ctx, createDraft,
		arg.DraftUuid,
		arg.TournamentClass,
		arg.RequestedBy,
		arg.Name,
		arg.Format,
		arg.TimeControl,
		arg.StartDatetime,
		arg.EndDatetime,
		arg.Timezone,
		arg.Capacity,
		arg.Visibility,
		arg.Prizes,
		arg.OrganizerTelegramID,
		arg.Rationale,
		arg.CreatedAt,
	)
	return err
}

const createOrganizer = `-- name: CreateOrganizer :exec
INSERT INTO organizers (
    telegram_id,
    name,
    logo_url,
    created_at
)
SELECT users.telegram_id, ?, ?, ?
FROM users
WHERE users.telegram_id = ?
AND is_whitelisted = 1
`

type CreateOrganizerParams struct {
	Name       sql.NullString
	LogoUrl    sql.NullString
	CreatedAt  sql.NullString
	TelegramID string
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) error {
	_, err := q.db.ExecContext(ctx, createOrganizer,
		arg.Name,
		arg.LogoUrl,
		arg.CreatedAt,
		arg.TelegramID,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    telegram_id,
    lichess_username,
    is_whitelisted,
    created_at
) VALUES (?, ?, 0, ?)
`

type CreateUserParams struct {
	TelegramID      string
	LichessUsername sql.NullString
	CreatedAt       sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.TelegramID, arg.LichessUsername, arg.CreatedAt)
	return err
}

const getDraft = `-- name: GetDraft :one
SELECT draft_uuid, tournament_class, requested_by, name, format, time_control, start_datetime, end_datetime, timezone, capacity, visibility, prizes, organizer_telegram_id, rationale, status, created_at, updated_at FROM tournament_drafts
WHERE draft_uuid = ?
`

func (q *Queries) GetDraft(ctx context.Context, draftUuid string) (TournamentDraft, error) {
	row := q.db.QueryRowContext(ctx, getDraft, draftUuid)
	var i TournamentDraft
	err := row.Scan(
		&i.DraftUuid,
		&i.TournamentClass,
		&i.RequestedBy,
		&i.Name,
		&i.Format,
		&i.TimeControl,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.Timezone,
		&i.Capacity,
		&i.Visibility,
		&i.Prizes,
		&i.OrganizerTelegramID,
		&i.Rationale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT telegram_id, lichess_username, is_whitelisted, created_at, updated_at FROM users
WHERE telegram_id = ?
`

func (q *Queries) GetUser(ctx context.Context, telegramID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, telegramID)
	var i User
	err := row.Scan(
		&i.TelegramID,
		&i.LichessUsername,
		&i.IsWhitelisted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
    entity_type,
    entity_id,
    action,
    performed_by,
    created_at
) VALUES (?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	EntityType  sql.NullString
	EntityID    sql.NullString
	Action      sql.NullString
	PerformedBy sql.NullString
	CreatedAt   sql.NullString
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.PerformedBy,
		arg.CreatedAt,
	)
	return err
}

const isOrganizer = `-- name: IsOrganizer :one
SELECT EXISTS(
    SELECT 1 FROM organizers WHERE telegram_id = ?
)
`

func (q *Queries) IsOrganizer(ctx context.Context, telegramID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isOrganizer, telegramID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isPresident = `-- name: IsPresident :one
SELECT EXISTS(
    SELECT 1 FROM presidents WHERE telegram_id = ?
)
`

func (q *Queries) IsPresident(ctx context.Context, telegramID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isPresident, telegramID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const publishDraft = `-- name: PublishDraft :exec
UPDATE tournament_drafts
SET status = 'published',
    updated_at = ?
WHERE draft_uuid = ?
AND status = 'approved'
`

type PublishDraftParams struct {
	UpdatedAt sql.NullString
	DraftUuid string
}

func (q *Queries) PublishDraft(ctx context.Context, arg PublishDraftParams) error {
	_, err := q.db.ExecContext(ctx, publishDraft, arg.UpdatedAt, arg.DraftUuid)
	return err
}

const removeWhitelist = `-- name: RemoveWhitelist :exec
UPDATE users
SET is_whitelisted = 0,
    updated_at = ?
WHERE telegram_id = ?
`

type RemoveWhitelistParams struct {
	UpdatedAt  sql.NullString
	TelegramID string
}

func (q *Queries) RemoveWhitelist(ctx context.Context, arg RemoveWhitelistParams) error {
	_, err := q.db.ExecContext(ctx, removeWhitelist, arg.UpdatedAt, arg.TelegramID)
	return err
}

const submitDraft = `-- name: SubmitDraft :exec
UPDATE tournament_drafts
SET status = 'submitted',
    updated_at = ?
WHERE draft_uuid = ?
AND requested_by = ?
`

type SubmitDraftParams struct {
	UpdatedAt   sql.NullString
	DraftUuid   string
	RequestedBy sql.NullString
}

func (q *Queries) SubmitDraft(ctx context.Context, arg SubmitDraftParams) error {
	_, err := q.db.ExecContext(ctx, submitDraft, arg.UpdatedAt, arg.DraftUuid, arg.RequestedBy)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE telegram_id = ?
)
`

func (q *Queries) UserExists(ctx context.Context, telegramID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, telegramID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const whitelistUser = `-- name: WhitelistUser :exec
UPDATE users
SET is_whitelisted = 1,
    updated_at = ?
WHERE telegram_id = ?
`

type WhitelistUserParams struct {
	UpdatedAt  sql.NullString
	TelegramID string
}

func (q *Queries) WhitelistUser(ctx context.Context, arg WhitelistUserParams) error {
	_, err := q.db.ExecContext(ctx, whitelistUser, arg.UpdatedAt, arg.TelegramID)
	return err
}
